[package]
name = "layer7-stress-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["full"] }
reqwest = { version = "0.11", features = ["stream"] }
clap = { version = "4.4", features = ["derive"] }

[[bin]]
name = "stress-test"
path = "babang.rs"
